

POST http://localhost:4000/api/patients/update/d88da104-8d39-43f4-a529-6382f66752b8
Content-Type: application/json

{
  "name": "Aayush Kumar Shakya",
  "email": "aayush.shakya@gmail.com",
  "address": "Baneshwor",
  "dateOfBirth": "2001-02-24",
  "registeredDate": "2026-01-01"
}